### ISSUE TITLE
problems with php 7

### ISSUE THREAD

**Issue by mediahaus** [hschottm/tags_news#1]
If I activate tag_news I get only a blank screen and in the log following message:

`Warning: Declaration of Contao\TagListNews::getRelatedTagList($for_tags) should be compatible with Contao\TagList::getRelatedTagList($for_tags, $blnExcludeUnpublishedItems = true) in system/modules/tags_news/classes/TagListNews.php on line 127

#0 system/modules/core/library/Contao/ClassLoader.php(148): __error(2, 'Declaration of ...', '/var/www/web...', 127, Array)
#1 system/modules/core/library/Contao/ClassLoader.php(148): include()
#2 [internal function]: Contao\ClassLoader::load('Contao\\TagListN...')
#3 system/modules/tags_news/modules/ModuleTagCloudNews.php(39): spl_autoload_call('Contao\\TagListN...')
#4 system/modules/core/elements/ContentModule.php(59): Contao\ModuleTagCloudNews->generate()
#5 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#6 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#7 system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#8 system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(true)
#11 system/modules/core/elements/ContentArticle.php(29): Contao\Controller::getArticle('69', false, true)
#12 system/modules/core/library/Contao/Controller.php(484): Contao\ContentArticle->generate()
#13 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#14 system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#15 system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#16 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#18 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 index.php(20): Contao\FrontendIndex->run()
#22 {main}

Warning: Declaration of Contao\TagListNews::getTagList() should be compatible with Contao\TagList::getTagList($blnExcludeUnpublishedItems = true) in system/modules/tags_news/classes/TagListNews.php on line 127

#0 system/modules/core/library/Contao/ClassLoader.php(148): __error(2, 'Declaration of ...', '/var/www/web...', 127, Array)
#1 system/modules/core/library/Contao/ClassLoader.php(148): include()
#2 [internal function]: Contao\ClassLoader::load('Contao\\TagListN...')
#3 system/modules/tags_news/modules/ModuleTagCloudNews.php(39): spl_autoload_call('Contao\\TagListN...')
#4 system/modules/core/elements/ContentModule.php(59): Contao\ModuleTagCloudNews->generate()
#5 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#6 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#7 system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#8 system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(true)
#11 system/modules/core/elements/ContentArticle.php(29): Contao\Controller::getArticle('69', false, true)
#12 system/modules/core/library/Contao/Controller.php(484): Contao\ContentArticle->generate()
#13 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#14 system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#15 system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#16 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#18 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 index.php(20): Contao\FrontendIndex->run()
#22 {main}

Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/web/html/system/modules/core/library/Contao/String.php on line 28`

Run Contao 3.5.19 on PHP 7.0.13
Contao runs without errors (use contao check)

**Comment by BugBuster1701** [comment]
Zum ersten Problem:
Erweiterung "tags_news", erbt von "tags", in der Erweiterung "tags":
```
tags/classes/TagList.php
public function getRelatedTagList($for_tags, $blnExcludeUnpublishedItems = true)

```
in der Erweiterung "tags_news":
```
tags_news/classes/TagListNews.php
public function getRelatedTagList($for_tags)

```
daher kommt es zur ersten Fehlermeldung. 
Identisch deklarieren, sollte Abhilfe schaffen, also in TagListNews genau so mit 2 Parameterm wie in TagList.

Die Nutzung der Klasse String kommt aus der Erweiterung "tags", nicht aus "tag_news":
https://github.com/hschottm/tags/blob/master/modules/ModuleTagCloud.php#L86

Da ich die Nutzung der Klasse aber sonst nicht gefunden habe, einfach mal testen in dem die Zeile auskommentiert wird.
`//$this->import('String');`

**Comment by mediahaus** [comment]
Danke, der Ansatz war richtig, beide gleich deklariert, nur habe ich die String-Klasse nicht auskommentiert sondern die Rückwärtskompatibilität von Contao genutzt und aus `$this->import('String');` wird dann: `$this->import('StringUtil');` - da hatte Leo nämlich schon mal was vorbereitet ;) 
--> system/modules/core/library/Contao/String.php
so sind alle Fehler und Warnungen weg.

Dank dir für den hilfreichen Tipp

**Comment by hschottm** [comment]
Behoben
