### ISSUE TITLE
Contao 4.4 

### ISSUE THREAD

**Issue by andre5tz** [hschottm/tags_news#2]
Hallo,

wird es eine Version für Contao 4.4 geben?
Ich nutze die tags_news bereits seit einiger Zeit unter Contao 4.4 und habe in der Anwendung keine Probleme festgestellt.

Es würde mich freuen, wenn auch die tags_news als bundle genutzt werden könnten. 

Viele Grüße und vielen Dank.
André

**Comment by hschottm** [comment]
Hallo André,

alle tags_xxxx Untererweiterungen zur tags-Erweiterung sind jetzt unter der tags-Erweiterung über den Composer für Contao 4.x verfügbar, ich habe die zusammengeführt, weil die Unterstützung für die tags z.B. für die news ohnehin in der tags-Erweiterung vorgenommen wird.

Die "komplette" tags-Erweiterung mit tags_news Unterstützung ist über https://packagist.org/packages/hschottm/tags mit dem Composer nutzbar
